baseURL = "http://echotrue.github.io/"
languageCode = "en-US"
defaultContentLanguage = "en"
title = "Axlrose's blog"

theme = "hugo-theme-learn"
copyright = "Axlrose"

[outputs]
home = ["HTML","RSS","JSON"]

[params]
  # Prefix URL to edit current page. Will display an "Edit this page" button on top right hand corner of every page.
  # Useful to give opportunity to people to create merge request for your doc.
  # See the config.toml file from this documentation site to have an example.
  editURL = ""
  # Author of the site, will be used in meta information
  author = "axlrose"
  # Description of the site, will be used in meta information
  description = "gohper"
  # Shows a checkmark for visited pages on the menu
  showVisitedLinks = true
  # Disable search function. It will hide search bar
  disableSearch = false
  # Javascript and CSS cache are automatically busted when new version of site is generated.
  # Set this to true to disable this behavior (some proxies don't handle well this optimization)
  disableAssetsBusting = false
  # Set this to true to disable copy-to-clipboard button for inline code.
  disableInlineCopyToClipBoard = true
  # A title for shortcuts in menu is set by default. Set this to true to disable it.
  disableShortcutsTitle = false
  # When using mulitlingual website, disable the switch language button.
  disableLanguageSwitchingButton = true
  # Hide breadcrumbs in the header and only show the current page title
  disableBreadcrumb = false
  # Hide Next and Previous page buttons normally displayed full height beside content
  disableNextPrev = false
  # Order sections in menu by "weight" or "title". Default to "weight"
  ordersectionsby = "weight"
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "blue"
  # Provide a list of custom css files to load relative from the `static/` folder in the site root.
#  custom_css = ["css/foo.css", "css/bar.css"]
  
[Languages]

[Languages.en]
title = "Axlrose's blog"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-tags'></i> Tags list"
url = "/tags"
weight = 1

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-camera'></i> About me"
url = "/about"
weight = 2

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/matcornic/hugo-theme-learn"
weight = 3

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> Hugo Documentation"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 4


#===========================================================法文
[Languages.fr]
title = "Documentation du thème Hugo Learn"
weight = 2
languageName = "Français"

[[Languages.fr.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Repo GitHub"
identifier = "ds"
url = "https://github.com/matcornic/hugo-theme-learn"
weight = 10

[[Languages.fr.menu.shortcuts]]
name = "<i class='fas fa-fw fa-camera'></i> Vitrine"
url = "/showcase"
weight = 11

[[Languages.fr.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> Documentation Hugo"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 20

[[Languages.fr.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Crédits"
url = "/credits"
weight = 30


#============================================= 中文
[Languages.zh]
title = "Hugo 主题的 Learn 文档"
weight = 3
languageName = "简体中文"

[[Languages.zh.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub 仓库"
identifier = "ds"
url = "https://github.com/matcornic/hugo-theme-learn"
weight = 10

[[Languages.zh.menu.shortcuts]]
name = "<i class='fas fa-fw fa-camera'></i> 展示区"
url = "/showcase"
weight = 11

[[Languages.zh.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> Hugo 文档"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 20

[[Languages.zh.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> 鸣谢"
url = "/credits"
weight = 30